name: Test Samples

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'

jobs:
  test:
    env:
      JBAL_VERSION: '2201.0.3'
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    - name: Download jBallerina deb
      run: |
          curl -L "https://github.com/ballerina-platform/ballerina-distribution/releases/download/v$JBAL_VERSION/ballerina-$JBAL_VERSION-swan-lake-linux-x64.deb" > $HOME/ballerina-$JBAL_VERSION-swan-lake-linux-x64.deb
    - name: Install jBallerina deb
      run: |
        sudo dpkg -i $HOME/ballerina-$JBAL_VERSION-swan-lake-linux-x64.deb
        echo "/usr/lib/ballerina/bin" >> $GITHUB_PATH
        echo "/usr/lib/ballerina/dependencies/jdk-11.0.8+10-jre/bin/java" >> $GITHUB_PATH
    - name: Run Tests
      run: |
        bal run proposaltracker
    - name: Commit files
      id: commit
      run: |
        git config --local user.email "anupama@wso2.com"
        git config --local user.name "anupama-pathirage"
        git add --all
        if [-z "$(git status --porcelain)"]; then
           echo "::set-output name=push::false"
        else
           git commit -m "Add changes" -a
           echo "::set-output name=push::true"
        fi
      shell: bash
    - name: Push changes
      if: steps.commit.outputs.push == 'true'
      uses: ad-m/github-push-action@master
      with:
         github_token: ${{ secrets.PROPOSAL_BOT_SECRET }}